tml = require 'tml'
fs = require 'fs'
lexer = require 'lexer'
builder = require 'builder'

global = window unless typeof(global) != 'undefined'

global.Builder = builder.Builder

global.fixture = (filename, ext = 'tml') ->
  filename = __dirname + "/fixtures/"+ filename + "." + ext
  fs.readFileSync(filename, "utf-8").trim()

global.dump_tree = (code) ->
  console.log (new lexer.Lexer).tokenize code
  
global.compile = (code) ->
  tml.compile(code).trim()
  
global.parse = (code) -> tml.parse code

global.build = (name, attrs, inner, depth) ->
  new builder.Builder(name, attrs, inner, depth)

# returns the document object model (in the form of `Builder` instances)
# generated by the specified script.
global.dom = (script) -> parse(script).compileDOM()

global.simulate = (dom, callback) ->
  sim = new tml.Simulator dom
  sim.start callback if callback
  sim

beforeEach ->
  $.reset()
  require './helpers/type_helper'
