#!/usr/bin/env bash

rm -rf ./out
mkdir ./out

coffee -c -o ./out ./lib/assets/javascripts

if [[ $? == 0 ]]
then
  # rename *.js.js => *.js
  # FIXME any better way?
  ruby -e "Dir['./out/**/*.js.js'].each { |f| system('mv', f, f.sub(/\.js$/, '')) }"
else
  exit 1
fi

